version: '3.3'

services:
  driver:
    network_mode: host
    environment:
    - DISPLAY=$DISPLAY
    - SSH_AUTH_SOCK=/ssh-agent
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=graphics
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/tmp/.docker.xauth
    volumes:
    - '/tmp/.X11-unix:/tmp/.X11-unix:rw'
    - '../:/spot'
    - '/tmp/.docker.xauth:/tmp/.docker.xauth'
    - './legion_connect.bash:/legion_connect.bash'
    - '~/.ssh/id_ed25519:/.ssh/id_ed25519'
      #- ${SSH_AUTH_SOCK}:/ssh-agent
    devices:
    - /dev/dri
    privileged: true
    # image: registry.ethz.ch/cvg/robotics/spot_ros:cvg-spot
    image: cvg/spot_ros_driver:latest
    command:  bash -c "source /catkin_ws/devel/setup.bash && roslaunch spot_driver driver.launch"
